# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alihv83\Desktop\arz_tala_sekkeh.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import regex
import requests
from bs4 import BeautifulSoup
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 208)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(130, 70, 161, 51))
        self.show.setObjectName("show")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(130, 140, 150, 21))
        self.result.setText("")
        self.result.setObjectName("result")
        self.tab_sekkeh = QtWidgets.QComboBox(self.centralwidget)
        self.tab_sekkeh.setGeometry(QtCore.QRect(10, 10, 91, 22))
        self.tab_sekkeh.setObjectName("tab_sekkeh")
        self.tab_sekkeh.addItem("")
        self.tab_sekkeh.setItemText(0, "")
        self.tab_sekkeh.addItem("")
        self.tab_sekkeh.addItem("")
        self.tab_sekkeh.addItem("")
        self.tab_sekkeh.addItem("")
        self.tab_sekkeh.addItem("")
        self.tab_sekkeh.addItem("")
        self.arz = QtWidgets.QLabel(self.centralwidget)
        self.arz.setGeometry(QtCore.QRect(350, 10, 51, 21))
        self.arz.setObjectName("arz")
        self.sekkeh = QtWidgets.QLabel(self.centralwidget)
        self.sekkeh.setGeometry(QtCore.QRect(90, 10, 51, 21))
        self.sekkeh.setObjectName("sekkeh")
        self.tab_tala = QtWidgets.QComboBox(self.centralwidget)
        self.tab_tala.setGeometry(QtCore.QRect(150, 10, 91, 22))
        self.tab_tala.setObjectName("tab_tala")
        self.tab_tala.addItem("")
        self.tab_tala.setItemText(0, "")
        self.tab_tala.addItem("")
        self.tab_tala.addItem("")
        self.tala = QtWidgets.QLabel(self.centralwidget)
        self.tala.setGeometry(QtCore.QRect(220, 10, 51, 21))
        self.tala.setObjectName("tala")
        self.tab_arz = QtWidgets.QComboBox(self.centralwidget)
        self.tab_arz.setGeometry(QtCore.QRect(280, 10, 91, 22))
        self.tab_arz.setObjectName("tab_arz")
        self.tab_arz.addItem("")
        self.tab_arz.setItemText(0, "")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        self.tab_arz.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.show.clicked.connect(self.results)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def results(self):
        app.processEvents()
        _translate = QtCore.QCoreApplication.translate

        site = requests.get("https://api.sunnyweb.ir/arz")
        text = site.text

        bs = BeautifulSoup(text, 'html.parser')

        table = bs.findAll('table', {'class':'table table-striped'})
        table = str(table)

        table_2 = regex.findall('>\d+,?\.?\d*,?\.?\d*,?\.?\d+<', table)

        arz_dic = {
        'bitcoin' : table_2[0],
        'tala_24' : table_2[1],
        'eterium' : table_2[2],
        'tala_18' : table_2[3],
        'sekke_emami' : table_2[4],
        'pond_england' : table_2[5],
        'sekke_bahar' : table_2[6],
        'euro' : table_2[7],
        'sekke_nim' : table_2[8],
        'dollar_amrican' : table_2[9],
        'sekke_rob' : table_2[10],
        'dollar_canada' : table_2[11],
        'sekke_gerami' : table_2[12],
        'dollar_australia' : table_2[13],
        'sekke_mesghali' : table_2[14],
        'dollar_newziland' : table_2[15],
        'dollar_sangapour' : table_2[16],
        'dollar_hongkong' : table_2[17],
        'derham_emarat' : table_2[18],
        'lir_turkey' : table_2[19],
        'lir_sourya' : table_2[20],
        'yoan_chin' : table_2[21],
        'yen_japan' : table_2[22],
        'frank_sooeis' : table_2[23],
        'cron_sooed' : table_2[24],
        'cron_danmark' : table_2[25],
        'cron_norweg' : table_2[26],
        'dinar_aragh' : table_2[27],
        'dinar_bahrain' : table_2[28],
        'dinar_kowait' : table_2[29],
        'dinar_bahrain' : table_2[30],
        'rial_arabestan' : table_2[31],
        'rial_qatar' : table_2[32],
        'rial_omman' : table_2[33],
        'roopie_india' : table_2[34],
        'roopie_pakestan' : table_2[35],
        'afghani_afghanestan' : table_2[36],
        'ringet_malesya' : table_2[37],
        'bat_tahiland' : table_2[38],
        'dram_armenia' : table_2[39],
        'lary_gorjya' : table_2[40]
        }

        countin = 'y'
        tab1_data = self.tab_arz.currentText()
        tab2_data = self.tab_tala.currentText()
        tab3_data = self.tab_sekkeh.currentText()
        if tab1_data == 'دلار آمریکا':
            self.result.setText(_translate("MainWindow", table_2[9]+tab1_data))
        if tab1_data == 'یورو':
            self.result.setText(_translate("MainWindow", table_2[7]+tab1_data))
        if tab1_data == 'پوند انگلیس':
            self.result.setText(_translate("MainWindow", table_2[5]+tab1_data))
        if tab1_data == 'دلار سنگاپور':
            self.result.setText(_translate("MainWindow", table_2[16]+tab1_data))
        if tab1_data == 'درهم امارات':
            self.result.setText(_translate("MainWindow", table_2[18]+tab1_data))
        if tab1_data == 'لیر ترکیه':
            self.result.setText(_translate("MainWindow", table_2[19]+tab1_data))
        if tab1_data == 'لیر سوریه':
            self.result.setText(_translate("MainWindow", table_2[20]+tab1_data))
        if tab1_data == 'یوئن چین':
            self.result.setText(_translate("MainWindow", table_2[21]+tab1_data))
        if tab1_data == 'ین ژاپن':
            self.result.setText(_translate("MainWindow", table_2[22]+tab1_data))
        if tab1_data == 'فرانک سوئیس':
            self.result.setText(_translate("MainWindow", table_2[23]+tab1_data))
        if tab1_data == 'کرون سوئد':
            self.result.setText(_translate("MainWindow", table_2[24]+tab1_data))
        if tab1_data == 'کرون دانمارک':
            self.result.setText(_translate("MainWindow", table_2[25]+tab1_data))
        if tab1_data == 'کرون نروژ':
            self.result.setText(_translate("MainWindow", table_2[26]+tab1_data))
        if tab1_data == 'دینار عراق':
            self.result.setText(_translate("MainWindow", table_2[27]+tab1_data))
        if tab1_data == 'دینار کویت':
            self.result.setText(_translate("MainWindow", table_2[29]+tab1_data))
        if tab1_data == 'دینار بحرین':
            self.result.setText(_translate("MainWindow", table_2[30]+tab1_data))
        if tab1_data == 'ریال عربستان':
            self.result.setText(_translate("MainWindow", table_2[31]+tab1_data))
        if tab1_data == 'ریال قطر':
            self.result.setText(_translate("MainWindow", table_2[32]+tab1_data))
        if tab1_data == 'ریال عمان':
            self.result.setText(_translate("MainWindow", table_2[33]+tab1_data))
        if tab1_data == 'دلار کانادا':
            self.result.setText(_translate("MainWindow", table_2[11]+tab1_data))
        if tab1_data == 'دلار استرالیا':
            self.result.setText(_translate("MainWindow", table_2[13]+tab1_data))
        if tab1_data == 'دلار نیوزلند':
            self.result.setText(_translate("MainWindow", table_2[15]+tab1_data))
        if tab1_data == 'روپیه هند':
            self.result.setText(_translate("MainWindow", table_2[34]+tab1_data))
        if tab1_data == 'روپیه پاکستان':
            self.result.setText(_translate("MainWindow", table_2[35]+tab1_data))
        if tab1_data == 'افغانی افغانستان':
            self.result.setText(_translate("MainWindow", table_2[36]+tab1_data))
        if tab1_data == 'رینگت مالزی':
            self.result.setText(_translate("MainWindow", table_2[37]+tab1_data))
        if tab1_data == 'بت تایلند':
            self.result.setText(_translate("MainWindow", table_2[38]+tab1_data))
        if tab1_data == 'درام ارمنستان':
            self.result.setText(_translate("MainWindow", table_2[39]+tab1_data))
        if tab1_data == 'لاری گرجستان':
            self.result.setText(_translate("MainWindow", table_2[40]+tab1_data))
        if tab1_data == 'بیت کوین':
            self.result.setText(_translate("MainWindow", table_2[0]+tab1_data))
        if tab1_data == 'اتریوم':
            self.result.setText(_translate("MainWindow", table_2[2]+tab1_data))
        if tab1_data == 'دلار هنگ کنک':
            self.result.setText(_translate("MainWindow", table_2[17]+tab1_data))
        if tab2_data == 'طلا 24 عیار':
            self.result.setText(_translate("MainWindow", table_2[1]+tab2_data))
        if tab2_data == 'طلا 18 عیار':
            self.result.setText(_translate("MainWindow", table_2[3]+tab2_data))
        if tab3_data == 'سکه بهار آزادی':
            self.result.setText(_translate("MainWindow", table_2[6]+tab3_data))
        if tab3_data == 'سکه امامی':
            self.result.setText(_translate("MainWindow", table_2[4]+tab3_data))
        if tab3_data == 'نیم سکه':
            self.result.setText(_translate("MainWindow", table_2[8]+tab3_data))
        if tab3_data == 'ربع سکه':
            self.result.setText(_translate("MainWindow", table_2[10]+tab3_data))
        if tab3_data == 'سکه گرمی':
            self.result.setText(_translate("MainWindow", table_2[12]+tab3_data))
        if tab3_data == 'سکه مثقالی':
            self.result.setText(_translate("MainWindow", table_2[14]+tab3_data))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "arz_tala_sekkeh"))
        self.show.setText(_translate("MainWindow", "مشاهده قیمت"))
        self.tab_sekkeh.setItemText(1, _translate("MainWindow", "سکه بهار آزادی"))
        self.tab_sekkeh.setItemText(2, _translate("MainWindow", "سکه امامی"))
        self.tab_sekkeh.setItemText(3, _translate("MainWindow", "نیم سکه"))
        self.tab_sekkeh.setItemText(4, _translate("MainWindow", "ربع سکه"))
        self.tab_sekkeh.setItemText(5, _translate("MainWindow", "سکه گرمی"))
        self.tab_sekkeh.setItemText(6, _translate("MainWindow", "سکه مثقالی"))
        self.arz.setText(_translate("MainWindow", "ارز"))
        self.sekkeh.setText(_translate("MainWindow", "سکه"))
        self.tab_tala.setItemText(1, _translate("MainWindow", "طلا 24 عیار"))
        self.tab_tala.setItemText(2, _translate("MainWindow", "طلا 18 عیار"))
        self.tala.setText(_translate("MainWindow", "طلا"))
        self.tab_arz.setItemText(1, _translate("MainWindow", "دلار آمریکا"))
        self.tab_arz.setItemText(2, _translate("MainWindow", "یورو"))
        self.tab_arz.setItemText(3, _translate("MainWindow", "پوند انگلیس"))
        self.tab_arz.setItemText(4, _translate("MainWindow", "دلار سنگاپور"))
        self.tab_arz.setItemText(5, _translate("MainWindow", "دلار هنگ کنک"))
        self.tab_arz.setItemText(6, _translate("MainWindow", "درهم امارات"))
        self.tab_arz.setItemText(7, _translate("MainWindow", "لیر ترکیه"))
        self.tab_arz.setItemText(8, _translate("MainWindow", "لیر سوریه"))
        self.tab_arz.setItemText(9, _translate("MainWindow", "یوئن چین"))
        self.tab_arz.setItemText(10, _translate("MainWindow", "ین ژاپن"))
        self.tab_arz.setItemText(11, _translate("MainWindow", "فرانک سوئیس"))
        self.tab_arz.setItemText(12, _translate("MainWindow", "کرون سوئد"))
        self.tab_arz.setItemText(13, _translate("MainWindow", "کرون دانمارک"))
        self.tab_arz.setItemText(14, _translate("MainWindow", "کرون نروژ"))
        self.tab_arz.setItemText(15, _translate("MainWindow", "دینار عراق"))
        self.tab_arz.setItemText(16, _translate("MainWindow", "دینار کویت"))
        self.tab_arz.setItemText(17, _translate("MainWindow", "دینار بحرین"))
        self.tab_arz.setItemText(18, _translate("MainWindow", "ریال عربستان"))
        self.tab_arz.setItemText(19, _translate("MainWindow", "ریال قطر"))
        self.tab_arz.setItemText(20, _translate("MainWindow", "ریال عمان"))
        self.tab_arz.setItemText(21, _translate("MainWindow", "دلار کانادا"))
        self.tab_arz.setItemText(22, _translate("MainWindow", "دلار استرالیا"))
        self.tab_arz.setItemText(23, _translate("MainWindow", "دلار نیوزلند"))
        self.tab_arz.setItemText(24, _translate("MainWindow", "روپیه هند"))
        self.tab_arz.setItemText(25, _translate("MainWindow", "روپیه پاکستان"))
        self.tab_arz.setItemText(26, _translate("MainWindow", "افغانی افغانستان"))
        self.tab_arz.setItemText(27, _translate("MainWindow", "رینگت مالزی"))
        self.tab_arz.setItemText(28, _translate("MainWindow", "بت تایلند"))
        self.tab_arz.setItemText(29, _translate("MainWindow", "درام ارمنستان"))
        self.tab_arz.setItemText(30, _translate("MainWindow", "لاری گرجستان"))
        self.tab_arz.setItemText(31, _translate("MainWindow", "بیت کوین"))
        self.tab_arz.setItemText(32, _translate("MainWindow", "اتریوم"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
